### ISSUE TITLE
Const declared in a failed cell still exits

### ISSUE THREAD

**Issue by levistringer** [Kings-Distributed-Systems/Bifrost#3]
If a const has been declared in a cell and then proceeds to fail you have to restart the entire runtime as you will get an error stating the variable already has been declared if you try and run it again 
`Error occured during script running/parsing:  evalmachine.<anonymous>:1
SyntaxError: Identifier 'compute' has already been declared
at evalmachine.<anonymous>:1:1
at Script.runInContext (vm.js:133:20)
at Object.runInContext (vm.js:311:6)
at Evaluator.evaluate (/usr/local/lib/python3.6/dist-packages/bifrost/main.js:139:18)
at Transform.inputStream._transform (/usr/local/lib/python3.6/dist-packages/bifrost/main.js:153:25)
at Transform._read (_stream_transform.js:190:10)
at Transform._write (_stream_transform.js:178:12)
at doWrite (_stream_writable.js:415:12)
at writeOrBuffer (_stream_writable.js:399:5)
at Transform.Writable.write (_stream_writable.js:299:11)`

**Comment by ccmcintyre-kingsds** [comment]
We will work to improve stability / recoverability of the NodeJS context, but it is otherwise expected (and intended) behaviour that a previously declared `const` cannot be redeclared.
