### ISSUE TITLE
Broken Pipe Errors

### ISSUE THREAD

**Issue by Jonah1234567** [Kings-Distributed-Systems/Bifrost#33]
I have encountered broken pipe errors in a variety of different settings including Windows 10, Ubuntu 22.04, and various versions of Python and Node. I have also experienced this error within Colab and a local Python environment. It seems that this error is a recurring issue with Bifrost across different platforms. This specific error trace was generated on Windows 10 with Node 16.15.0 and Python 3.8.8.

Error:

```
Error: \\?\C:\Users\jonah\OneDrive\Desktop\DCL Work\Bifrost\node_modules\@raygun-nickj\mmap-io\build\binding\Release\node-v93-win32-x64\mmap_io.node is not a valid Win32 application.
\\?\C:\Users\jonah\OneDrive\Desktop\DCL Work\Bifrost\node_modules\@raygun-nickj\mmap-io\build\binding\Release\node-v93-win32-x64\mmap_io.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\jonah\OneDrive\Desktop\DCL Work\Bifrost\node_modules\@raygun-nickj\mmap-io\dist\mmap-io.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[WinError 5] Access is denied
Pipe broke and was restarted
Could not run script
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    result_set = job.exec()
  File "C:\Users\jonah\anaconda3\lib\site-packages\bifrost\Job.py", line 417, in exec
    results = self.__dcp_run()
  File "C:\Users\jonah\anaconda3\lib\site-packages\bifrost\Job.py", line 367, in __dcp_run
    result_set = node_output['jobOutput']
TypeError: 'NoneType' object is not subscriptable

```

**Comment by ccmcintyre-kingsds** [comment]
Related to #30 and #31, likely caused by the way the mmap tools on the Node.js side are interacting with various node versions in the recent past, sometimes during installation and sometimes at runtime, at least under the conditions that we have been using it in. High priority issue. Solution may involve editing, downgrading, or even replacing the mmap library currently being used.
