### ISSUE TITLE
Scheduler is not defined

### ISSUE THREAD

**Issue by Jonah1234567** [Kings-Distributed-Systems/Bifrost#35]
Scheduler is not defined is triggered by running a script that ends up pausing in the uploading phase again after stopping the initial job. Instances of this error may occur in other scenarios. This error will force the user to disconnect and delete runtime on Colab to remedy it, which places a sizeable burden on the user. This error was found in Colab with python 3.7.13 and Node 16.15.0.

Link to the code: 
https://colab.research.google.com/drive/1byKsAHpZVlq0QU3FN8PYs0la2Z-vWy12?usp=sharing

Steps to reproduce:
1. Run an initial job that gets stuck at the uploading phase
2. Run the job again

Error:

```
proceeding with currently installed version of dcp-client
Error occured during script running/parsing:  evalmachine.<anonymous>:2
if ( !globalThis.dcpClient ) globalThis.dcpClient = require("dcp-client").init(scheduler);
^
ReferenceError: scheduler is not defined
at evalmachine.<anonymous>:2:88
at Script.runInContext (node:vm:139:12)
at Object.runInContext (node:vm:289:6)
at Evaluator.evaluate (/usr/local/lib/python3.7/dist-packages/bifrost/main.js:210:18)
at Transform.inputStream._transform (/usr/local/lib/python3.7/dist-packages/bifrost/main.js:239:25)
Error occured during script running/parsing:  ReferenceError: dcp_multiplier is not defined
at evalmachine.<anonymous>:263:25
at evalmachine.<anonymous>:344:3
at Script.runInContext (node:vm:139:12)
at Object.runInContext (node:vm:289:6)
at Evaluator.evaluate (/usr/local/lib/python3.7/dist-packages/bifrost/main.js:210:18)
at Transform.inputStream._transform (/usr/local/lib/python3.7/dist-packages/bifrost/main.js:239:25)
at Transform._write (node:internal/streams/transform:184:23)
at writeOrBuffer (node:internal/streams/writable:389:12)
at _write (node:internal/streams/writable:330:10)
at Transform.Writable.write (node:internal/streams/writable:334:10)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-28-81c4bce090](https://localhost:8080/#)
10 
     11 # EXEC
---> 12 result_set = job.exec()
     13 # DISPLAY RESULTS
     14 #print (result_set)

1 frames
[/usr/local/lib/python3.7/dist-packages/bifrost/Job.py](https://localhost:8080/#) in __dcp_run(self)
    365         node_output = node.run(self.python_deploy, run_parameters)
    366 
--> 367         result_set = node_output['jobOutput']
    368 
    369         for result_index, result_slice in enumerate(result_set):

KeyError: 'jobOutput'
```

**Comment by ccmcintyre-kingsds** [comment]
Related to #32 ("Running Identical Jobs Fails"), but a sufficiently distinct expression of that issue to warrant independent investigation, as the failure state reached in this case is much worse than poor error handling. This appears to involve the shared memory being entirely lost by the Node.js process, when a hanging cell is re-run. That has broader implications, and should be handled as a well-communicated error in the short term, and *potentially* fixed in the longer term such that the process is durable to multiple runs of a single cell even from unresolved states. We'll want to talk with Wes et al as to whether that is desirable behavior, from an architectural and UX standpoint, and how to best implement that behaviour if so.
